[window]

opacity = 0.9
blur = true
padding.x = 10
padding.y = 10

[font]
normal = {family = "0xProto Nerd font", style = "Regular"}
bold = {family = "0xProto Nerd font", style = "Bold"}
italic = {family = "0xProto Nerd font", style = "Italic"}
size = 19.0

[keyboard]
bindings = [
	{ key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]

