[mgr]
cwd            = { fg = "#1e66f5" }
find_keyword   = { fg = "#df8e1d", italic = true }
find_position  = { fg = "#fe640b", bg = "reset", bold = true }
symlink_target = { fg = "#179299", italic = true }

marker_copied   = { fg = "#40a02b", bg = "#40a02b" }
marker_cut      = { fg = "#d20f39", bg = "#d20f39" }
marker_marked   = { fg = "#179299", bg = "#179299" }
marker_selected = { fg = "#df8e1d", bg = "#df8e1d" }

count_copied   = { fg = "#eff1f5", bg = "#40a02b" }
count_cut      = { fg = "#eff1f5", bg = "#d20f39" }
count_selected = { fg = "#eff1f5", bg = "#df8e1d" }

border_symbol = "│"
border_style  = { fg = "#bcc0cc" }

[indicator]
parent  = { fg = "#9ca0b0" }
current = { fg = "#4c4f69" }
preview = { fg = "#9ca0b0" }

[tabs]
active   = { fg = "#eff1f5", bg = "#1e66f5", bold = true }
inactive = { fg = "#4c4f69", bg = "#ccd0da" }

[mode]
normal_main = { fg = "#eff1f5", bg = "#1e66f5", bold = true }
normal_alt  = { fg = "#1e66f5", bg = "#ccd0da" }
select_main = { fg = "#eff1f5", bg = "#40a02b", bold = true }
select_alt  = { fg = "#40a02b", bg = "#ccd0da" }
unset_main  = { fg = "#eff1f5", bg = "#8839ef", bold = true }
unset_alt   = { fg = "#8839ef", bg = "#ccd0da" }

[status]
perm_type  = { fg = "#8839ef" }
perm_read  = { fg = "#df8e1d" }
perm_write = { fg = "#d20f39" }
perm_exec  = { fg = "#40a02b" }
perm_sep   = { fg = "#bcc0cc" }

progress_label  = { fg = "#4c4f69", bold = true }
progress_normal = { fg = "#1e66f5", bg = "#eff1f5" }
progress_error  = { fg = "#d20f39", bg = "#eff1f5" }

[input]
border   = { fg = "#1e66f5" }
title    = { fg = "#4c4f69" }
value    = { fg = "#4c4f69" }
selected = { fg = "#eff1f5", bg = "#1e66f5" }

[pick]
border   = { fg = "#1e66f5" }
active   = { fg = "#8839ef", bold = true }
inactive = { fg = "#9ca0b0" }

[cmp]
border   = { fg = "#1e66f5" }
active   = { fg = "#eff1f5", bg = "#1e66f5" }
inactive = { fg = "#9ca0b0" }

[tasks]
border  = { fg = "#1e66f5" }
title   = { fg = "#4c4f69" }
hovered = { fg = "#8839ef", underline = true }

[which]
cols            = 3
mask            = { bg = "#e6e9ef" }
cand            = { fg = "#04a5e5" }
rest            = { fg = "#9ca0b0" }
desc            = { fg = "#8839ef" }
separator       = "  "
separator_style = { fg = "#bcc0cc" }

[notify]
title_info  = { fg = "#1e66f5" }
title_warn  = { fg = "#df8e1d" }
title_error = { fg = "#d20f39" }
icon_info  = ""
icon_warn  = ""
icon_error = ""

[spot]
border = { fg = "#1e66f5" }
title  = { fg = "#1e66f5" }
