gui:
  nerdFontsVersion: "3"
keybinding:
  commits:
    moveUpCommit: 'K'
    moveDownCommit: 'J'
git:
  pagers:
    - colorArg: always
      pager: delta --paging=never --side-by-side --line-numbers
      useConfig: false
customCommands:
  - key: 'E'
    description: 'Add empty commit'
    context: 'commits'
    command: 'git commit --allow-empty -m "empty commit"'
    loadingText: 'Committing empty commit...'
