#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "Tobias Kaestner"
email = "tobias.kaestner@inovex.de"

[ui]
editor = "vim"

[aliases]
prs = ["log","-r","ancestors(trunk(), 20) & merges()","-n","6"]

[revset-aliases]
'landed(n)' = "ancestors(trunk(), n) & merges()"
